workflows:
  ios-workflow:
    name: iOS Build and Deploy
    max_build_duration: 120
    
    environment:
      xcode: 13.3
      flutter: stable
      ios_signing:
        provisioning_profiles:
          #- development_profile_cskmparents
          - distribution_profile_cskmparents
        certificates:
          #- development_certificate
          - production_certificate
    integrations:
      app_store_connect: APIKeyAdminAccess
    scripts:
      - script: xcode-project use-profiles
      - script: flutter packages pub get
      - name: Flutter build ipa and automatic versioning
        script: flutter build ipa --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_app_store: true
      email:
        recipients:
          - sssoft2023@gmail.com