// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASCC5bonaiTb4bfr92YUpqJsy_KkSOC1g',
    appId: '1:152408515642:web:0379313f03ac575bc2c103',
    messagingSenderId: '152408515642',
    projectId: 'cskm-parents',
    authDomain: 'cskm-parents.firebaseapp.com',
    storageBucket: 'cskm-parents.appspot.com',
    measurementId: 'G-4WESY1FVQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdd07iylu9NvYosnEZ0zPyF6mGlHB5wwg',
    appId: '1:152408515642:android:a0343fdcd0dffbedc2c103',
    messagingSenderId: '152408515642',
    projectId: 'cskm-parents',
    storageBucket: 'cskm-parents.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUEKiaFvEHJ0yO_zUS9Z8Y5aol-kPuOUQ',
    appId: '1:152408515642:ios:5a2b6c51d3d3aedcc2c103',
    messagingSenderId: '152408515642',
    projectId: 'cskm-parents',
    storageBucket: 'cskm-parents.appspot.com',
    iosBundleId: 'cskm.com.cskmparents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUEKiaFvEHJ0yO_zUS9Z8Y5aol-kPuOUQ',
    appId: '1:152408515642:ios:494c00e76246e11ec2c103',
    messagingSenderId: '152408515642',
    projectId: 'cskm-parents',
    storageBucket: 'cskm-parents.appspot.com',
    iosBundleId: 'cskm.com.cskmparents.RunnerTests',
  );
}
